// Mocks generated by Mockito 5.4.6 from annotations
// in linzaivision_primary/test/migration/complex_state_migration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:linzaivision_primary/models/goal.dart' as _i4;
import 'package:linzaivision_primary/repository/goal_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalRepository extends _i1.Mock implements _i2.GoalRepository {
  MockGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Goal>> getGoals({int? parentId}) => (super.noSuchMethod(
        Invocation.method(
          #getGoals,
          [],
          {#parentId: parentId},
        ),
        returnValue: _i3.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
      ) as _i3.Future<List<_i4.Goal>>);

  @override
  _i3.Future<_i4.Goal?> getGoal(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getGoal,
          [id],
        ),
        returnValue: _i3.Future<_i4.Goal?>.value(),
      ) as _i3.Future<_i4.Goal?>);

  @override
  _i3.Future<int> insertGoal(_i4.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #insertGoal,
          [goal],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateGoal(_i4.Goal? goal) => (super.noSuchMethod(
        Invocation.method(
          #updateGoal,
          [goal],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteGoal(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteGoal,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Goal>> getGoalTree() => (super.noSuchMethod(
        Invocation.method(
          #getGoalTree,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Goal>>.value(<_i4.Goal>[]),
      ) as _i3.Future<List<_i4.Goal>>);

  @override
  _i3.Future<void> batchInsertGoalTree(List<_i4.Goal>? rootGoals) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchInsertGoalTree,
          [rootGoals],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
